import Ember from 'ember';
import config from '../config/environment';
import { commandFactory, CMD_TYPES } from '../models/commands';

/* global saveAs */

export default Ember.Component.extend({
    tagName: 'ul',
    classNames: ['script-builder', 'sections'],
    showNewCommandEditor: false,
    isDownloadAvailable: typeof Blob !== 'undefined',
    commandKeys: Object.keys(CMD_TYPES),
    filename: 'qc-generator.qc',
    commands: [
        commandFactory(CMD_TYPES.$modelname, '// Generated by http://blackmesasource/qc v' + config.version)
    ],

    change: function (e) {
        var $target = Ember.$(e.target);

        if ($target.is('#new-command select')) {
            this.get('commands').pushObject(commandFactory($target.val()));
            this.set('showNewCommandEditor', false);
        }
    },

    toArray: function() {
        var arr = [];

        this.get('commands').forEach(function (cmd) {
            var output,
                comment = cmd.get('comment');

            if (comment) {
                arr.push(comment);
            }

            output = cmd.get('output');
            arr.push(comment ? output + '\r\n' : output);
        });

        return arr;
    },

    toString: function () {
        return this.toArray().join('\r\n');
    },

    actions: {
        addCommand: function () {
            this.set('showNewCommandEditor', true);
        },

        deleteCommand: function (command) {
            this.get('commands').removeObject(command);
        },

        replaceCommand: function (command, type) {
            var commands = this.get('commands'),
                index = commands.indexOf(command);

            commands.removeAt(index);
            commands.insertAt(index, commandFactory(type, command.get('comment')));
        },

        download: function () {
            saveAs(new Blob([this.toString()], { type: 'text/plain;charset=utf-8' }), this.get('filename'));
        },

        copyToClipboard: function () {
            //var event = new ClipboardEvent('copy', { dataType: 'text/plain', data: 'hello from the clipboard!' });
            //document.dispatchEvent(event);
        }
    }
});
