import Ember from 'ember';
import config from '../config/environment';
import Command from '../models/command';

/* global saveAs */

export default Ember.Component.extend({
    tagName: 'ul',
    classNames: ['script-builder', 'sections'],
    showNewCommandEditor: false,
    isDownloadAvailable: typeof Blob !== 'undefined',
    filename: 'generated.qc',
    validationTrigger: 0,

    commands: Object.keys(Command.COMMANDS).map(function (key) {
        return Ember.$.extend(true, {}, Command.COMMANDS[key]);
    }),

    script: [
        Command.createByType(
            Command.TYPES.$modelname,
            '// Generated by http://blackmesasource/qc c' + config.version
        )
    ],

    change: function (e) {
        let $target = Ember.$(e.target);

        if ($target.is('#new-command select')) {
            this.get('script').pushObject(Command.createByType($target.val()));
            this.set('showNewCommandEditor', false);
        }
    },

    validate: function () {
        let instance = this;

        return new Ember.RSVP.Promise(function (resolve, reject) {
            instance.incrementProperty('validationTrigger');

            Ember.run.scheduleOnce('afterRender', instance, function () {
                if (Ember.$(this.get('element')).find('.is-invalid').length) {
                    reject();
                } else {
                    resolve();
                }
            });
        });
    },

    toArray: function () {
        let arr = [];

        this.get('script').forEach(function (cmd) {
            let output,
                comment = cmd.get('comment');

            if (comment) {
                arr.push(comment);
            }

            output = cmd.get('output');
            arr.push(comment ? output + '\r\n' : output);
        });

        return arr;
    },

    toString: function () {
        return this.toArray().join('\r\n');
    },

    actions: {
        addCommand: function () {
            this.set('showNewCommandEditor', true);
        },

        deleteCommand: function (command) {
            this.get('script').removeObject(command);
        },

        replaceCommand: function (command, type) {
            let script = this.get('script'),
                index = script.indexOf(command);

            script.removeAt(index);
            script.insertAt(index, Command.createByType(type, command.get('comment')));
        },

        download: function () {
            let instance = this;

            this.validate().then(function () {
                let script = instance.toString(),
                    filename = instance.get('filename');

                saveAs(new Blob([script], { type: 'text/plain;charset=utf-8' }), filename);
            }, function () {
                console.log('no go on download');
            });
        },

        copyToClipboard: function () {
            this.validate().then(function () {
                //var event = new ClipboardEvent('copy', { dataType: 'text/plain', data: 'hello from the clipboard!' });
                //document.dispatchEvent(event);
            }, function () {
                console.log('no go on copy');
            });
        }
    }
});
