import Ember from 'ember';
import config from '../config/environment';
import Command from '../models/command';

export default Ember.Route.extend({
    model: function () {
        return [
            Command.createFromPrefab(
                '$modelname',
                '// Generated by http://blackmesasource.com/qc v' + config.version
            )
        ];
    }
});
